apiVersion: v1
kind: Service
metadata:
  annotations:
  name: graphiql
spec:
  ports:
  - name: graphiql
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: graphiql
  sessionAffinity: None
  type: ClusterIP
